---
secretManagement:
  serviceAccountName: "workload"
  secretProviderClassName: "azure-keyvault-secrets-provider"
  tenantId: "d400387a-212f-43ea-ac7f-77aa12d7977e"
  clientId: "706d9217-bc27-4786-9149-15627a279f1d"

  keyVault:
    name: "kvunibeidghrunner6rwm"
    objects: 
      - name: "id-csvcghes-pat"
        value: "github_token"

github:
  githubConfigUrl: "https://github.unibe.ch/enterprises/university-of-bern"
  githubConfigSecret: "id-ghec-runner"
  runnerScaleSetName: "dependabot"
  runnerGroup: "arc-runners"

  minRunners: 0
  maxRunners: 10
  containerMode:
    type: "dind"

  template:
    spec:
      containers:
        - name: runner
          image: "ghcr.io/id-unibe-ch/cloud-azure-ghrunner-image:main"
          imagePullPolicy: Always
          command: ["/home/runner/run.sh"]

