---
githubConfigUrl: "https://github.unibe.ch/kevin-studer/esb-mqparis"
githubConfigSecret: "kevin-studer-ghes-runner"
runnerScaleSetName: "kevin-studer-ghes-runner"


minRunners: 0
maxRunners: 10
containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: "ghcr.io/id-unibe-ch/cloud-azure-ghrunner-image:main"
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
