---
secretManagement:
  serviceAccountName: "workload"
  secretProviderClassName: "azure-keyvault-secrets-provider"
  tenantId: "d400387a-212f-43ea-ac7f-77aa12d7977e"
  clientId: "1e792cf7-2906-4290-a088-b414afbf5bfa"

  keyVault:
    name: "kv-id-ghrunner-kv-switze"
    objects: 
      - name: "id-cloud-runners-app-id"
        value: "github_app_id"
      - name: "id-cloud-runners-idunibech-installation-id"
        value: "github_app_installation_id"
      - name: "id-cloud-runners-private-key"
        value: "github_app_private_key"

github:
  githubConfigUrl: "https://github.com/id-unibe-ch"
  githubConfigSecret: "id-ghec-runner"
  runnerScaleSetName: "id-runner"
  runnerGroup: "arc-runners"

  minRunners: 3
  maxRunners: 30
  containerMode:
    type: "dind"

  template:
    spec:
      containers:
        - name: runner
          image: "ghcr.io/id-unibe-ch/cloud-azure-ghrunner-image:main"
          imagePullPolicy: Always
          command: ["/home/runner/run.sh"]
