---
secretManagement:
  serviceAccountName: "workload"
  secretProviderClassName: "azure-keyvault-secrets-provider"
  tenantId: "d400387a-212f-43ea-ac7f-77aa12d7977e"
  clientId: "976321fd-b26c-4a8e-af2f-1be22f0b8a13"

  keyVault:
    name: "kv-id-ghrunner-kv-switze"
    objects: 
      - name: "id-cloud-runners-app-id"
        value: "github_app_id"
      - name: "id-cloud-runners-idciunibech-installation-id"
        value: "github_app_installation_id"
      - name: "id-cloud-runners-private-key"
        value: "github_app_private_key"

github:
  githubConfigUrl: "https://github.com/idci-unibe-ch"
  githubConfigSecret: "idci-ghec-runner"
  runnerScaleSetName: "idci-runner"
  runnerGroup: "arc-runners"

  minRunners: 1
  maxRunners: 10
  containerMode:
    type: "dind"

  template:
    spec:
      containers:
        - name: runner
          image: "ghcr.io/id-unibe-ch/cloud-azure-ghrunner-image:main"
          imagePullPolicy: Always
          command: ["/home/runner/run.sh"]
